<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Angela Liu">

<title>Class 09: Structural Bioinformatics 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="class09_files/libs/clipboard/clipboard.min.js"></script>
<script src="class09_files/libs/quarto-html/quarto.js"></script>
<script src="class09_files/libs/quarto-html/popper.min.js"></script>
<script src="class09_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="class09_files/libs/quarto-html/anchor.min.js"></script>
<link href="class09_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="class09_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="class09_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="class09_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="class09_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Class 09: Structural Bioinformatics 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Angela Liu </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="what-is-in-the-pdb-anyway" class="level2">
<h2 class="anchored" data-anchor-id="what-is-in-the-pdb-anyway">What is in the PDB anyway?</h2>
<p>The main database of biomolecular structures is called the PDB and is available at www.rcsb.org.</p>
<p>Let’s begin by seeing what is in this database:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pdbstats &lt;- read.csv("/Users/angelaliu/Documents/bimm143/class09/PDB.csv", row.names = 1)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pdbstats <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"pdb.csv"</span>, <span class="at">row.names =</span> <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pdbstats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          X.ray    EM    NMR Multiple.methods Neutron Other
Protein (only)          152,809 9,421 12,117              191      72    32
Protein/Oligosaccharide   9,008 1,654     32                7       1     0
Protein/NA                8,061 2,944    281                6       0     0
Nucleic acid (only)       2,602    77  1,433               12       2     1
Other                       163     9     31                0       0     0
Oligosaccharide (only)       11     0      6                1       0     4
                          Total
Protein (only)          174,642
Protein/Oligosaccharide  10,702
Protein/NA               11,292
Nucleic acid (only)       4,127
Other                       203
Oligosaccharide (only)       22</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q1: What percentage of structures in the PDB are solved by X-Ray and Electron Microscopy.</p>
</blockquote>
<p>There’s an issue where the data inputs are all strings, as opposed to integers. We use <code>gsub()</code> to remove the commas from the numbers and <code>as.numeric()</code> to convert the strings to integers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove the commas from the numbers </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#convert string to numbers</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>n.xray <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, pdbstats<span class="sc">$</span>X.ray)))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>n.xray</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 172654</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n.em <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, pdbstats<span class="sc">$</span>EM)))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>n.em</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14105</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, pdbstats<span class="sc">$</span>Total)))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 200988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculating percentages with two significant figures</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>perXray <span class="ot">&lt;-</span> <span class="fu">round</span>((n.xray<span class="sc">/</span>total) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>perEM <span class="ot">&lt;-</span> <span class="fu">round</span>((n.em<span class="sc">/</span>total) <span class="sc">*</span> <span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>perXray</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>perEM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.02</code></pre>
</div>
</div>
<p>85.9% of the structures are solved by X-Ray while 7.02% are solved by EM.</p>
<blockquote class="blockquote">
<p>Q2: What proportion of structures in the PDB are protein?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">""</span>, pdbstats<span class="sc">$</span>Total))<span class="sc">/</span>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8689175473 0.0532469600 0.0561824587 0.0205335642 0.0010100105
[6] 0.0001094593</code></pre>
</div>
</div>
<p>The first element represents the proportion of structures that are protein (only), 86.9%.</p>
<blockquote class="blockquote">
<p>Q3: Type HIV in the PDB website search box on the home page and determine how many HIV-1 protease structures are in the current PDB?</p>
</blockquote>
<p>There are 200,988 search results from HIV-1 protease structures. It’s hard to straightforwardly find all HIV-1 protease structures with plain text on the database.</p>
</section>
<section id="visualizing-the-hiv-1-protease-structure" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-hiv-1-protease-structure">Visualizing the HIV-1 Protease Structure</h2>
<blockquote class="blockquote">
<p>Q4: Water molecules normally have 3 atoms. Why do we see just one atom per water molecule in this structure?</p>
</blockquote>
<p>We only see one atom per water molecule because hydrogen is too small for the resolution.</p>
<blockquote class="blockquote">
<p>Q5: There is a critical “conserved” water molecule in the binding site. Can you identify this water molecule? What residue number does this water molecule have?</p>
</blockquote>
<p>Yes, the water molecule is at residue number 308.</p>
<p><img src="water.png" class="img-fluid"></p>
<blockquote class="blockquote">
<p>Q6: Generate and save a figure clearly showing the two distinct chains of HIV-protease along with the ligand. You might also consider showing the catalytic residues ASP 25 in each chain and the critical water (we recommend “Ball &amp; Stick” for these side-chains). Add this figure to your Quarto document. Discussion Topic: Can you think of a way in which indinavir, or even larger ligands and substrates, could enter the binding site?</p>
</blockquote>
<p><img src="1HSG.png" class="img-fluid"> <img src="zoomIn.png" class="img-fluid" alt="A zoomed in photo"></p>
</section>
<section id="intro-to-bio3d" class="level2">
<h2 class="anchored" data-anchor-id="intro-to-bio3d">Intro to Bio3D</h2>
<p>We will use the <code>bio3d</code> package for this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bio3d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read a PDB file from the online database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pdb <span class="ot">&lt;-</span> <span class="fu">read.pdb</span>(<span class="st">"1hsg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Note: Accessing on-line PDB file</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a quick summary of the pdb file</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pdb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Call:  read.pdb(file = "1hsg")

   Total Models#: 1
     Total Atoms#: 1686,  XYZs#: 5058  Chains#: 2  (values: A B)

     Protein Atoms#: 1514  (residues/Calpha atoms#: 198)
     Nucleic acid Atoms#: 0  (residues/phosphate atoms#: 0)

     Non-protein/nucleic Atoms#: 172  (residues: 128)
     Non-protein/nucleic resid values: [ HOH (127), MK1 (1) ]

   Protein sequence:
      PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMSLPGRWKPKMIGGIGGFIKVRQYD
      QILIEICGHKAIGTVLVGPTPVNIIGRNLLTQIGCTLNFPQITLWQRPLVTIKIGGQLKE
      ALLDTGADDTVLEEMSLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTVLVGPTP
      VNIIGRNLLTQIGCTLNF

+ attr: atom, xyz, seqres, helix, sheet,
        calpha, remark, call</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pdb<span class="sc">$</span>atom)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  type eleno elety  alt resid chain resno insert      x      y     z o     b
1 ATOM     1     N &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 29.361 39.686 5.862 1 38.10
2 ATOM     2    CA &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 30.307 38.663 5.319 1 40.62
3 ATOM     3     C &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 29.760 38.071 4.022 1 42.64
4 ATOM     4     O &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 28.600 38.302 3.676 1 43.40
5 ATOM     5    CB &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 30.508 37.541 6.342 1 37.87
6 ATOM     6    CG &lt;NA&gt;   PRO     A     1   &lt;NA&gt; 29.296 37.591 7.162 1 38.40
  segid elesy charge
1  &lt;NA&gt;     N   &lt;NA&gt;
2  &lt;NA&gt;     C   &lt;NA&gt;
3  &lt;NA&gt;     C   &lt;NA&gt;
4  &lt;NA&gt;     O   &lt;NA&gt;
5  &lt;NA&gt;     C   &lt;NA&gt;
6  &lt;NA&gt;     C   &lt;NA&gt;</code></pre>
</div>
</div>
<p>What is the first residue 3 letter code and 1 letter code?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># residue 3 letter code</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pdb<span class="sc">$</span>atom<span class="sc">$</span>resid[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PRO"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># residue w 1 letter code</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aa321</span>(pdb<span class="sc">$</span>atom<span class="sc">$</span>resid[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q7: How many amino acid residues are there in this pdb object?</p>
</blockquote>
<p>198 amino acid residues</p>
<blockquote class="blockquote">
<p>Q8: Name one of the two non-protein residues?</p>
</blockquote>
<p>water(HOH) and MK1</p>
<blockquote class="blockquote">
<p>Q9: How many protein chains are in this structure?</p>
</blockquote>
<p>There are 2 protein chains in the structure.</p>
</section>
<section id="predicting-functional-motions-of-a-single-structure" class="level2">
<h2 class="anchored" data-anchor-id="predicting-functional-motions-of-a-single-structure">Predicting functional motions of a single structure</h2>
<p>Reading in a new PDB structure of adenylate kinase (PDB code: 6s36) and using normal mode analysis (NMA) to predict the protein flexibility and potential functional motions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>adk <span class="ot">&lt;-</span> <span class="fu">read.pdb</span>(<span class="st">"6s36"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Note: Accessing on-line PDB file
   PDB has ALT records, taking A only, rm.alt=TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>adk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Call:  read.pdb(file = "6s36")

   Total Models#: 1
     Total Atoms#: 1898,  XYZs#: 5694  Chains#: 1  (values: A)

     Protein Atoms#: 1654  (residues/Calpha atoms#: 214)
     Nucleic acid Atoms#: 0  (residues/phosphate atoms#: 0)

     Non-protein/nucleic Atoms#: 244  (residues: 244)
     Non-protein/nucleic resid values: [ CL (3), HOH (238), MG (2), NA (1) ]

   Protein sequence:
      MRIILLGAPGAGKGTQAQFIMEKYGIPQISTGDMLRAAVKSGSELGKQAKDIMDAGKLVT
      DELVIALVKERIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFDVPDELIVDKI
      VGRRVHAPSGRVYHVKFNPPKVEGKDDVTGEELTTRKDDQEETVRKRLVEYHQMTAPLIG
      YYSKEAEAGNTKYAKVDGTKPVAEVRADLEKILG

+ attr: atom, xyz, seqres, helix, sheet,
        calpha, remark, call</code></pre>
</div>
</div>
<p>Normal mode analysis (NMA) is a structural bioinformatics method to predict protein flexibility and potential functional motions (a.k.a. conformational changes).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform flexiblity prediction</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nma</span>(adk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Building Hessian...        Done in 0.05 seconds.
 Diagonalizing Hessian...   Done in 0.696 seconds.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The peaks show the most flexible residues.</p>
<p>To view a “movie” of these predicted motions we can generate a molecular “trajectory” with the <code>mktrj()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mktrj</span>(m, <span class="at">file=</span><span class="st">"adk_m7.pdb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-4-comparative-structure-analysis-of-adk" class="level2">
<h2 class="anchored" data-anchor-id="section-4-comparative-structure-analysis-of-adk">Section 4: Comparative structure analysis of Adk</h2>
<p>Today we are continuing were we left off last day building towards completing the loop from biomolecular structural data to our new analysis methods like PCA and clustering.</p>
<p>Prepping for this section and downloading in the R console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install packages in the R console NOT your Rmd/Quarto file</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("bio3d")</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("devtools")</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("BiocManager")</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co">#BiocManager::install("msa")</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_bitbucket("Grantlab/bio3d-view")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Q10. Which of the packages above is found only on BioConductor and not CRAN?</p>
</blockquote>
<p>msa is found only in BioConductor and not CRAN as it uses a different line of code to download specifically in BiocManager, <code>BiocManager::install("msa")</code>.</p>
<blockquote class="blockquote">
<p>Q11. Which of the above packages is not found on BioConductor or CRAN?:</p>
</blockquote>
<p>bio3d-view</p>
<blockquote class="blockquote">
<p>Q12. True or False? Functions from the devtools package can be used to install packages from GitHub and BitBucket?</p>
</blockquote>
<p>TRUE</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bio3d)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>aa <span class="ot">&lt;-</span> <span class="fu">get.seq</span>(<span class="st">"1ake_A"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.seq("1ake_A"): Removing existing file: seqs.fasta</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Fetching... Please wait. Done.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q13. How many amino acids are in this sequence, i.e.&nbsp;how long is this sequence?</p>
</blockquote>
<p>There are 214 amino acid sequences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Blast or hmmer search </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># b &lt;- blast.pdb(aa)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I could save and load my blast results next time so I don’t need to run the search every time.</p>
<p><code>saveRDS()</code> makes a compressed small size object that contains BLAST results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># comment out this code because it needs the b as reference for when it runs the first time</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># saveRDS(b, file = "blast_results.RDS")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"blast_results.RDS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A summary plot of our BLAST results</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a summary of search results</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>hits <span class="ot">&lt;-</span> <span class="fu">plot</span>(b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  * Possible cutoff values:    197 -3 
            Yielding Nhits:    16 96 

  * Chosen cutoff value of:    197 
            Yielding Nhits:    16 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>hits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$hits
   pdb.id   acc      group
1  "1AKE_A" "1AKE_A" "1"  
2  "4X8M_A" "4X8M_A" "1"  
3  "6S36_A" "6S36_A" "1"  
4  "6RZE_A" "6RZE_A" "1"  
5  "4X8H_A" "4X8H_A" "1"  
6  "3HPR_A" "3HPR_A" "1"  
7  "1E4V_A" "1E4V_A" "1"  
8  "5EJE_A" "5EJE_A" "1"  
9  "1E4Y_A" "1E4Y_A" "1"  
10 "3X2S_A" "3X2S_A" "1"  
11 "6HAP_A" "6HAP_A" "1"  
12 "6HAM_A" "6HAM_A" "1"  
13 "4K46_A" "4K46_A" "1"  
14 "4NP6_A" "4NP6_A" "1"  
15 "3GMT_A" "3GMT_A" "1"  
16 "4PZL_A" "4PZL_A" "1"  

$pdb.id
 [1] "1AKE_A" "4X8M_A" "6S36_A" "6RZE_A" "4X8H_A" "3HPR_A" "1E4V_A" "5EJE_A"
 [9] "1E4Y_A" "3X2S_A" "6HAP_A" "6HAM_A" "4K46_A" "4NP6_A" "3GMT_A" "4PZL_A"

$acc
 [1] "1AKE_A" "4X8M_A" "6S36_A" "6RZE_A" "4X8H_A" "3HPR_A" "1E4V_A" "5EJE_A"
 [9] "1E4Y_A" "3X2S_A" "6HAP_A" "6HAM_A" "4K46_A" "4NP6_A" "3GMT_A" "4PZL_A"

$inds
 [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

attr(,"class")
[1] "blast"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List out some 'top hits'</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hits<span class="sc">$</span>pdb.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1AKE_A" "4X8M_A" "6S36_A" "6RZE_A" "4X8H_A" "3HPR_A"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Download related PDB files</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># path makes a subfolder called "pdbs" where the pdb files will be downloaded into, gzip makes compressed zip files</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>files <span class="ot">&lt;-</span> <span class="fu">get.pdb</span>(hits<span class="sc">$</span>pdb.id, <span class="at">path=</span><span class="st">"pdbs"</span>, <span class="at">split=</span><span class="cn">TRUE</span>, <span class="at">gzip=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/1AKE.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/4X8M.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/6S36.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/6RZE.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/4X8H.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/3HPR.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/1E4V.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/5EJE.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/1E4Y.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/3X2S.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/6HAP.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/6HAM.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/4K46.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/4NP6.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/3GMT.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in get.pdb(hits$pdb.id, path = "pdbs", split = TRUE, gzip = TRUE):
pdbs/4PZL.pdb.gz exists. Skipping download</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=========                                                             |  12%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |==========================                                            |  38%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |============================================                          |  62%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |=============================================================         |  88%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
</div>
<p>Next we are going to align and superpose all these structures:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Align related PDBs</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># fit = TRUE to superpose</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># use msa package to do the alignment; diff alignment methods</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>pdbs <span class="ot">&lt;-</span> <span class="fu">pdbaln</span>(files, <span class="at">fit =</span> <span class="cn">TRUE</span>, <span class="at">exefile=</span><span class="st">"msa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading PDB files:
pdbs/split_chain/1AKE_A.pdb
pdbs/split_chain/4X8M_A.pdb
pdbs/split_chain/6S36_A.pdb
pdbs/split_chain/6RZE_A.pdb
pdbs/split_chain/4X8H_A.pdb
pdbs/split_chain/3HPR_A.pdb
pdbs/split_chain/1E4V_A.pdb
pdbs/split_chain/5EJE_A.pdb
pdbs/split_chain/1E4Y_A.pdb
pdbs/split_chain/3X2S_A.pdb
pdbs/split_chain/6HAP_A.pdb
pdbs/split_chain/6HAM_A.pdb
pdbs/split_chain/4K46_A.pdb
pdbs/split_chain/4NP6_A.pdb
pdbs/split_chain/3GMT_A.pdb
pdbs/split_chain/4PZL_A.pdb
   PDB has ALT records, taking A only, rm.alt=TRUE
..   PDB has ALT records, taking A only, rm.alt=TRUE
.   PDB has ALT records, taking A only, rm.alt=TRUE
..   PDB has ALT records, taking A only, rm.alt=TRUE
..   PDB has ALT records, taking A only, rm.alt=TRUE
....   PDB has ALT records, taking A only, rm.alt=TRUE
.   PDB has ALT records, taking A only, rm.alt=TRUE
....

Extracting sequences

pdb/seq: 1   name: pdbs/split_chain/1AKE_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 2   name: pdbs/split_chain/4X8M_A.pdb 
pdb/seq: 3   name: pdbs/split_chain/6S36_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 4   name: pdbs/split_chain/6RZE_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 5   name: pdbs/split_chain/4X8H_A.pdb 
pdb/seq: 6   name: pdbs/split_chain/3HPR_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 7   name: pdbs/split_chain/1E4V_A.pdb 
pdb/seq: 8   name: pdbs/split_chain/5EJE_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 9   name: pdbs/split_chain/1E4Y_A.pdb 
pdb/seq: 10   name: pdbs/split_chain/3X2S_A.pdb 
pdb/seq: 11   name: pdbs/split_chain/6HAP_A.pdb 
pdb/seq: 12   name: pdbs/split_chain/6HAM_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 13   name: pdbs/split_chain/4K46_A.pdb 
   PDB has ALT records, taking A only, rm.alt=TRUE
pdb/seq: 14   name: pdbs/split_chain/4NP6_A.pdb 
pdb/seq: 15   name: pdbs/split_chain/3GMT_A.pdb 
pdb/seq: 16   name: pdbs/split_chain/4PZL_A.pdb </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>pdbs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                1        .         .         .         40 
[Truncated_Name:1]1AKE_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:2]4X8M_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:3]6S36_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:4]6RZE_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:5]4X8H_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:6]3HPR_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:7]1E4V_A.pdb    ----------MRIILLGAPVAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:8]5EJE_A.pdb    ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:9]1E4Y_A.pdb    ----------MRIILLGALVAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:10]3X2S_A.pdb   ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:11]6HAP_A.pdb   ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:12]6HAM_A.pdb   ----------MRIILLGAPGAGKGTQAQFIMEKYGIPQIS
[Truncated_Name:13]4K46_A.pdb   ----------MRIILLGAPGAGKGTQAQFIMAKFGIPQIS
[Truncated_Name:14]4NP6_A.pdb   --------NAMRIILLGAPGAGKGTQAQFIMEKFGIPQIS
[Truncated_Name:15]3GMT_A.pdb   ----------MRLILLGAPGAGKGTQANFIKEKFGIPQIS
[Truncated_Name:16]4PZL_A.pdb   TENLYFQSNAMRIILLGAPGAGKGTQAKIIEQKYNIAHIS
                                          **^*****  *******  *  *^ *  ** 
                                1        .         .         .         40 

                               41        .         .         .         80 
[Truncated_Name:1]1AKE_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:2]4X8M_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:3]6S36_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:4]6RZE_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:5]4X8H_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:6]3HPR_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:7]1E4V_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:8]5EJE_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDACKLVTDELVIALVKE
[Truncated_Name:9]1E4Y_A.pdb    TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVKE
[Truncated_Name:10]3X2S_A.pdb   TGDMLRAAVKSGSELGKQAKDIMDCGKLVTDELVIALVKE
[Truncated_Name:11]6HAP_A.pdb   TGDMLRAAVKSGSELGKQAKDIMDAGKLVTDELVIALVRE
[Truncated_Name:12]6HAM_A.pdb   TGDMLRAAIKSGSELGKQAKDIMDAGKLVTDEIIIALVKE
[Truncated_Name:13]4K46_A.pdb   TGDMLRAAIKAGTELGKQAKSVIDAGQLVSDDIILGLVKE
[Truncated_Name:14]4NP6_A.pdb   TGDMLRAAIKAGTELGKQAKAVIDAGQLVSDDIILGLIKE
[Truncated_Name:15]3GMT_A.pdb   TGDMLRAAVKAGTPLGVEAKTYMDEGKLVPDSLIIGLVKE
[Truncated_Name:16]4PZL_A.pdb   TGDMIRETIKSGSALGQELKKVLDAGELVSDEFIIKIVKD
                                ****^*  ^* *^ **   *  ^*   ** *  ^^ ^^^^ 
                               41        .         .         .         80 

                               81        .         .         .         120 
[Truncated_Name:1]1AKE_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:2]4X8M_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:3]6S36_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:4]6RZE_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:5]4X8H_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:6]3HPR_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:7]1E4V_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:8]5EJE_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:9]1E4Y_A.pdb    RIAQEDCRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:10]3X2S_A.pdb   RIAQEDSRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:11]6HAP_A.pdb   RICQEDSRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:12]6HAM_A.pdb   RICQEDSRNGFLLDGFPRTIPQADAMKEAGINVDYVLEFD
[Truncated_Name:13]4K46_A.pdb   RIAQDDCAKGFLLDGFPRTIPQADGLKEVGVVVDYVIEFD
[Truncated_Name:14]4NP6_A.pdb   RIAQADCEKGFLLDGFPRTIPQADGLKEMGINVDYVIEFD
[Truncated_Name:15]3GMT_A.pdb   RLKEADCANGYLFDGFPRTIAQADAMKEAGVAIDYVLEID
[Truncated_Name:16]4PZL_A.pdb   RISKNDCNNGFLLDGVPRTIPQAQELDKLGVNIDYIVEVD
                                *^   *   *^* ** **** **  ^   *^ ^**^^* * 
                               81        .         .         .         120 

                              121        .         .         .         160 
[Truncated_Name:1]1AKE_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:2]4X8M_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:3]6S36_A.pdb    VPDELIVDKIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:4]6RZE_A.pdb    VPDELIVDAIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:5]4X8H_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:6]3HPR_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDGTG
[Truncated_Name:7]1E4V_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:8]5EJE_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:9]1E4Y_A.pdb    VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:10]3X2S_A.pdb   VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:11]6HAP_A.pdb   VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:12]6HAM_A.pdb   VPDELIVDRIVGRRVHAPSGRVYHVKFNPPKVEGKDDVTG
[Truncated_Name:13]4K46_A.pdb   VADSVIVERMAGRRAHLASGRTYHNVYNPPKVEGKDDVTG
[Truncated_Name:14]4NP6_A.pdb   VADDVIVERMAGRRAHLPSGRTYHVVYNPPKVEGKDDVTG
[Truncated_Name:15]3GMT_A.pdb   VPFSEIIERMSGRRTHPASGRTYHVKFNPPKVEGKDDVTG
[Truncated_Name:16]4PZL_A.pdb   VADNLLIERITGRRIHPASGRTYHTKFNPPKVADKDDVTG
                                *    ^^^ ^ *** *  *** **  ^*****  *** ** 
                              121        .         .         .         160 

                              161        .         .         .         200 
[Truncated_Name:1]1AKE_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:2]4X8M_A.pdb    EELTTRKDDQEETVRKRLVEWHQMTAPLIGYYSKEAEAGN
[Truncated_Name:3]6S36_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:4]6RZE_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:5]4X8H_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAALIGYYSKEAEAGN
[Truncated_Name:6]3HPR_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:7]1E4V_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:8]5EJE_A.pdb    EELTTRKDDQEECVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:9]1E4Y_A.pdb    EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:10]3X2S_A.pdb   EELTTRKDDQEETVRKRLCEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:11]6HAP_A.pdb   EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:12]6HAM_A.pdb   EELTTRKDDQEETVRKRLVEYHQMTAPLIGYYSKEAEAGN
[Truncated_Name:13]4K46_A.pdb   EDLVIREDDKEETVLARLGVYHNQTAPLIAYYGKEAEAGN
[Truncated_Name:14]4NP6_A.pdb   EDLVIREDDKEETVRARLNVYHTQTAPLIEYYGKEAAAGK
[Truncated_Name:15]3GMT_A.pdb   EPLVQRDDDKEETVKKRLDVYEAQTKPLITYYGDWARRGA
[Truncated_Name:16]4PZL_A.pdb   EPLITRTDDNEDTVKQRLSVYHAQTAKLIDFYRNFSSTNT
                                * *  * ** *^ *  **  ^   *  ** ^*         
                              161        .         .         .         200 

                              201        .         .      227 
[Truncated_Name:1]1AKE_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:2]4X8M_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:3]6S36_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:4]6RZE_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:5]4X8H_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:6]3HPR_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:7]1E4V_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:8]5EJE_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:9]1E4Y_A.pdb    T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:10]3X2S_A.pdb   T--KYAKVDGTKPVAEVRADLEKILG-
[Truncated_Name:11]6HAP_A.pdb   T--KYAKVDGTKPVCEVRADLEKILG-
[Truncated_Name:12]6HAM_A.pdb   T--KYAKVDGTKPVCEVRADLEKILG-
[Truncated_Name:13]4K46_A.pdb   T--QYLKFDGTKAVAEVSAELEKALA-
[Truncated_Name:14]4NP6_A.pdb   T--QYLKFDGTKQVSEVSADIAKALA-
[Truncated_Name:15]3GMT_A.pdb   E-------NGLKAPA-----YRKISG-
[Truncated_Name:16]4PZL_A.pdb   KIPKYIKINGDQAVEKVSQDIFDQLNK
                                         *                  
                              201        .         .      227 

Call:
  pdbaln(files = files, fit = TRUE, exefile = "msa")

Class:
  pdbs, fasta

Alignment dimensions:
  16 sequence rows; 227 position columns (204 non-gap, 23 gap) 

+ attr: xyz, resno, b, chain, id, ali, resid, sse, call</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to show the alignment</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>pdbs<span class="sc">$</span>ali</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
pdbs/split_chain/1AKE_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/4X8M_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/6S36_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/6RZE_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/4X8H_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/3HPR_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/1E4V_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/5EJE_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/1E4Y_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/3X2S_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/6HAP_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/6HAM_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/4K46_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/4NP6_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "N"  "A"  
pdbs/split_chain/3GMT_A.pdb "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  "-"  
pdbs/split_chain/4PZL_A.pdb "T"  "E"  "N"  "L"  "Y"  "F"  "Q"  "S"  "N"  "A"  
                            [,11] [,12] [,13] [,14] [,15] [,16] [,17] [,18]
pdbs/split_chain/1AKE_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/4X8M_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/6S36_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/6RZE_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/4X8H_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/3HPR_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/1E4V_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/5EJE_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/1E4Y_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/3X2S_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/6HAP_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/6HAM_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/4K46_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/4NP6_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/3GMT_A.pdb "M"   "R"   "L"   "I"   "L"   "L"   "G"   "A"  
pdbs/split_chain/4PZL_A.pdb "M"   "R"   "I"   "I"   "L"   "L"   "G"   "A"  
                            [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
pdbs/split_chain/1AKE_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/4X8M_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/6S36_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/6RZE_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/4X8H_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/3HPR_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/1E4V_A.pdb "P"   "V"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/5EJE_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/1E4Y_A.pdb "L"   "V"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/3X2S_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/6HAP_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/6HAM_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/4K46_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/4NP6_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/3GMT_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
pdbs/split_chain/4PZL_A.pdb "P"   "G"   "A"   "G"   "K"   "G"   "T"   "Q"  
                            [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34]
pdbs/split_chain/1AKE_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/4X8M_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/6S36_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/6RZE_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/4X8H_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/3HPR_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/1E4V_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/5EJE_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/1E4Y_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/3X2S_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/6HAP_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/6HAM_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "Y"  
pdbs/split_chain/4K46_A.pdb "A"   "Q"   "F"   "I"   "M"   "A"   "K"   "F"  
pdbs/split_chain/4NP6_A.pdb "A"   "Q"   "F"   "I"   "M"   "E"   "K"   "F"  
pdbs/split_chain/3GMT_A.pdb "A"   "N"   "F"   "I"   "K"   "E"   "K"   "F"  
pdbs/split_chain/4PZL_A.pdb "A"   "K"   "I"   "I"   "E"   "Q"   "K"   "Y"  
                            [,35] [,36] [,37] [,38] [,39] [,40] [,41] [,42]
pdbs/split_chain/1AKE_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/4X8M_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/6S36_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/6RZE_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/4X8H_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/3HPR_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/1E4V_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/5EJE_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/1E4Y_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/3X2S_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/6HAP_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/6HAM_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/4K46_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/4NP6_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/3GMT_A.pdb "G"   "I"   "P"   "Q"   "I"   "S"   "T"   "G"  
pdbs/split_chain/4PZL_A.pdb "N"   "I"   "A"   "H"   "I"   "S"   "T"   "G"  
                            [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
pdbs/split_chain/1AKE_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/4X8M_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/6S36_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/6RZE_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/4X8H_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/3HPR_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/1E4V_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/5EJE_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/1E4Y_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/3X2S_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/6HAP_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/6HAM_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "I"   "K"  
pdbs/split_chain/4K46_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "I"   "K"  
pdbs/split_chain/4NP6_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "I"   "K"  
pdbs/split_chain/3GMT_A.pdb "D"   "M"   "L"   "R"   "A"   "A"   "V"   "K"  
pdbs/split_chain/4PZL_A.pdb "D"   "M"   "I"   "R"   "E"   "T"   "I"   "K"  
                            [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58]
pdbs/split_chain/1AKE_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/4X8M_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/6S36_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/6RZE_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/4X8H_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/3HPR_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/1E4V_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/5EJE_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/1E4Y_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/3X2S_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/6HAP_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/6HAM_A.pdb "S"   "G"   "S"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/4K46_A.pdb "A"   "G"   "T"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/4NP6_A.pdb "A"   "G"   "T"   "E"   "L"   "G"   "K"   "Q"  
pdbs/split_chain/3GMT_A.pdb "A"   "G"   "T"   "P"   "L"   "G"   "V"   "E"  
pdbs/split_chain/4PZL_A.pdb "S"   "G"   "S"   "A"   "L"   "G"   "Q"   "E"  
                            [,59] [,60] [,61] [,62] [,63] [,64] [,65] [,66]
pdbs/split_chain/1AKE_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/4X8M_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/6S36_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/6RZE_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/4X8H_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/3HPR_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/1E4V_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/5EJE_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "C"  
pdbs/split_chain/1E4Y_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/3X2S_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "C"   "G"  
pdbs/split_chain/6HAP_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/6HAM_A.pdb "A"   "K"   "D"   "I"   "M"   "D"   "A"   "G"  
pdbs/split_chain/4K46_A.pdb "A"   "K"   "S"   "V"   "I"   "D"   "A"   "G"  
pdbs/split_chain/4NP6_A.pdb "A"   "K"   "A"   "V"   "I"   "D"   "A"   "G"  
pdbs/split_chain/3GMT_A.pdb "A"   "K"   "T"   "Y"   "M"   "D"   "E"   "G"  
pdbs/split_chain/4PZL_A.pdb "L"   "K"   "K"   "V"   "L"   "D"   "A"   "G"  
                            [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
pdbs/split_chain/1AKE_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/4X8M_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/6S36_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/6RZE_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/4X8H_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/3HPR_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/1E4V_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/5EJE_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/1E4Y_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/3X2S_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/6HAP_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "L"   "V"  
pdbs/split_chain/6HAM_A.pdb "K"   "L"   "V"   "T"   "D"   "E"   "I"   "I"  
pdbs/split_chain/4K46_A.pdb "Q"   "L"   "V"   "S"   "D"   "D"   "I"   "I"  
pdbs/split_chain/4NP6_A.pdb "Q"   "L"   "V"   "S"   "D"   "D"   "I"   "I"  
pdbs/split_chain/3GMT_A.pdb "K"   "L"   "V"   "P"   "D"   "S"   "L"   "I"  
pdbs/split_chain/4PZL_A.pdb "E"   "L"   "V"   "S"   "D"   "E"   "F"   "I"  
                            [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82]
pdbs/split_chain/1AKE_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/4X8M_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/6S36_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/6RZE_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/4X8H_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/3HPR_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/1E4V_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/5EJE_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/1E4Y_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/3X2S_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/6HAP_A.pdb "I"   "A"   "L"   "V"   "R"   "E"   "R"   "I"  
pdbs/split_chain/6HAM_A.pdb "I"   "A"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/4K46_A.pdb "L"   "G"   "L"   "V"   "K"   "E"   "R"   "I"  
pdbs/split_chain/4NP6_A.pdb "L"   "G"   "L"   "I"   "K"   "E"   "R"   "I"  
pdbs/split_chain/3GMT_A.pdb "I"   "G"   "L"   "V"   "K"   "E"   "R"   "L"  
pdbs/split_chain/4PZL_A.pdb "I"   "K"   "I"   "V"   "K"   "D"   "R"   "I"  
                            [,83] [,84] [,85] [,86] [,87] [,88] [,89] [,90]
pdbs/split_chain/1AKE_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/4X8M_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/6S36_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/6RZE_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/4X8H_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/3HPR_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/1E4V_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/5EJE_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/1E4Y_A.pdb "A"   "Q"   "E"   "D"   "C"   "R"   "N"   "G"  
pdbs/split_chain/3X2S_A.pdb "A"   "Q"   "E"   "D"   "S"   "R"   "N"   "G"  
pdbs/split_chain/6HAP_A.pdb "C"   "Q"   "E"   "D"   "S"   "R"   "N"   "G"  
pdbs/split_chain/6HAM_A.pdb "C"   "Q"   "E"   "D"   "S"   "R"   "N"   "G"  
pdbs/split_chain/4K46_A.pdb "A"   "Q"   "D"   "D"   "C"   "A"   "K"   "G"  
pdbs/split_chain/4NP6_A.pdb "A"   "Q"   "A"   "D"   "C"   "E"   "K"   "G"  
pdbs/split_chain/3GMT_A.pdb "K"   "E"   "A"   "D"   "C"   "A"   "N"   "G"  
pdbs/split_chain/4PZL_A.pdb "S"   "K"   "N"   "D"   "C"   "N"   "N"   "G"  
                            [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
pdbs/split_chain/1AKE_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/4X8M_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/6S36_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/6RZE_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/4X8H_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/3HPR_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/1E4V_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/5EJE_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/1E4Y_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/3X2S_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/6HAP_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/6HAM_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/4K46_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/4NP6_A.pdb "F"   "L"   "L"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/3GMT_A.pdb "Y"   "L"   "F"   "D"   "G"   "F"   "P"   "R"  
pdbs/split_chain/4PZL_A.pdb "F"   "L"   "L"   "D"   "G"   "V"   "P"   "R"  
                            [,99] [,100] [,101] [,102] [,103] [,104] [,105]
pdbs/split_chain/1AKE_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/4X8M_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/6S36_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/6RZE_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/4X8H_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/3HPR_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/1E4V_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/5EJE_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/1E4Y_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/3X2S_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/6HAP_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/6HAM_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/4K46_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "G"   
pdbs/split_chain/4NP6_A.pdb "T"   "I"    "P"    "Q"    "A"    "D"    "G"   
pdbs/split_chain/3GMT_A.pdb "T"   "I"    "A"    "Q"    "A"    "D"    "A"   
pdbs/split_chain/4PZL_A.pdb "T"   "I"    "P"    "Q"    "A"    "Q"    "E"   
                            [,106] [,107] [,108] [,109] [,110] [,111] [,112]
pdbs/split_chain/1AKE_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/4X8M_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/6S36_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/6RZE_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/4X8H_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/3HPR_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/1E4V_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/5EJE_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/1E4Y_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/3X2S_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/6HAP_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/6HAM_A.pdb "M"    "K"    "E"    "A"    "G"    "I"    "N"   
pdbs/split_chain/4K46_A.pdb "L"    "K"    "E"    "V"    "G"    "V"    "V"   
pdbs/split_chain/4NP6_A.pdb "L"    "K"    "E"    "M"    "G"    "I"    "N"   
pdbs/split_chain/3GMT_A.pdb "M"    "K"    "E"    "A"    "G"    "V"    "A"   
pdbs/split_chain/4PZL_A.pdb "L"    "D"    "K"    "L"    "G"    "V"    "N"   
                            [,113] [,114] [,115] [,116] [,117] [,118] [,119]
pdbs/split_chain/1AKE_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/4X8M_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/6S36_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/6RZE_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/4X8H_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/3HPR_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/1E4V_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/5EJE_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/1E4Y_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/3X2S_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/6HAP_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/6HAM_A.pdb "V"    "D"    "Y"    "V"    "L"    "E"    "F"   
pdbs/split_chain/4K46_A.pdb "V"    "D"    "Y"    "V"    "I"    "E"    "F"   
pdbs/split_chain/4NP6_A.pdb "V"    "D"    "Y"    "V"    "I"    "E"    "F"   
pdbs/split_chain/3GMT_A.pdb "I"    "D"    "Y"    "V"    "L"    "E"    "I"   
pdbs/split_chain/4PZL_A.pdb "I"    "D"    "Y"    "I"    "V"    "E"    "V"   
                            [,120] [,121] [,122] [,123] [,124] [,125] [,126]
pdbs/split_chain/1AKE_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/4X8M_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/6S36_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/6RZE_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/4X8H_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/3HPR_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/1E4V_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/5EJE_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/1E4Y_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/3X2S_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/6HAP_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/6HAM_A.pdb "D"    "V"    "P"    "D"    "E"    "L"    "I"   
pdbs/split_chain/4K46_A.pdb "D"    "V"    "A"    "D"    "S"    "V"    "I"   
pdbs/split_chain/4NP6_A.pdb "D"    "V"    "A"    "D"    "D"    "V"    "I"   
pdbs/split_chain/3GMT_A.pdb "D"    "V"    "P"    "F"    "S"    "E"    "I"   
pdbs/split_chain/4PZL_A.pdb "D"    "V"    "A"    "D"    "N"    "L"    "L"   
                            [,127] [,128] [,129] [,130] [,131] [,132] [,133]
pdbs/split_chain/1AKE_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/4X8M_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/6S36_A.pdb "V"    "D"    "K"    "I"    "V"    "G"    "R"   
pdbs/split_chain/6RZE_A.pdb "V"    "D"    "A"    "I"    "V"    "G"    "R"   
pdbs/split_chain/4X8H_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/3HPR_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/1E4V_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/5EJE_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/1E4Y_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/3X2S_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/6HAP_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/6HAM_A.pdb "V"    "D"    "R"    "I"    "V"    "G"    "R"   
pdbs/split_chain/4K46_A.pdb "V"    "E"    "R"    "M"    "A"    "G"    "R"   
pdbs/split_chain/4NP6_A.pdb "V"    "E"    "R"    "M"    "A"    "G"    "R"   
pdbs/split_chain/3GMT_A.pdb "I"    "E"    "R"    "M"    "S"    "G"    "R"   
pdbs/split_chain/4PZL_A.pdb "I"    "E"    "R"    "I"    "T"    "G"    "R"   
                            [,134] [,135] [,136] [,137] [,138] [,139] [,140]
pdbs/split_chain/1AKE_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/4X8M_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/6S36_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/6RZE_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/4X8H_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/3HPR_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/1E4V_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/5EJE_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/1E4Y_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/3X2S_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/6HAP_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/6HAM_A.pdb "R"    "V"    "H"    "A"    "P"    "S"    "G"   
pdbs/split_chain/4K46_A.pdb "R"    "A"    "H"    "L"    "A"    "S"    "G"   
pdbs/split_chain/4NP6_A.pdb "R"    "A"    "H"    "L"    "P"    "S"    "G"   
pdbs/split_chain/3GMT_A.pdb "R"    "T"    "H"    "P"    "A"    "S"    "G"   
pdbs/split_chain/4PZL_A.pdb "R"    "I"    "H"    "P"    "A"    "S"    "G"   
                            [,141] [,142] [,143] [,144] [,145] [,146] [,147]
pdbs/split_chain/1AKE_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/4X8M_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/6S36_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/6RZE_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/4X8H_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/3HPR_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/1E4V_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/5EJE_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/1E4Y_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/3X2S_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/6HAP_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/6HAM_A.pdb "R"    "V"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/4K46_A.pdb "R"    "T"    "Y"    "H"    "N"    "V"    "Y"   
pdbs/split_chain/4NP6_A.pdb "R"    "T"    "Y"    "H"    "V"    "V"    "Y"   
pdbs/split_chain/3GMT_A.pdb "R"    "T"    "Y"    "H"    "V"    "K"    "F"   
pdbs/split_chain/4PZL_A.pdb "R"    "T"    "Y"    "H"    "T"    "K"    "F"   
                            [,148] [,149] [,150] [,151] [,152] [,153] [,154]
pdbs/split_chain/1AKE_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/4X8M_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/6S36_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/6RZE_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/4X8H_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/3HPR_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/1E4V_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/5EJE_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/1E4Y_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/3X2S_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/6HAP_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/6HAM_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/4K46_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/4NP6_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/3GMT_A.pdb "N"    "P"    "P"    "K"    "V"    "E"    "G"   
pdbs/split_chain/4PZL_A.pdb "N"    "P"    "P"    "K"    "V"    "A"    "D"   
                            [,155] [,156] [,157] [,158] [,159] [,160] [,161]
pdbs/split_chain/1AKE_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/4X8M_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/6S36_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/6RZE_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/4X8H_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/3HPR_A.pdb "K"    "D"    "D"    "G"    "T"    "G"    "E"   
pdbs/split_chain/1E4V_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/5EJE_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/1E4Y_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/3X2S_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/6HAP_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/6HAM_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/4K46_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/4NP6_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/3GMT_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
pdbs/split_chain/4PZL_A.pdb "K"    "D"    "D"    "V"    "T"    "G"    "E"   
                            [,162] [,163] [,164] [,165] [,166] [,167] [,168]
pdbs/split_chain/1AKE_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/4X8M_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/6S36_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/6RZE_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/4X8H_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/3HPR_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/1E4V_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/5EJE_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/1E4Y_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/3X2S_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/6HAP_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/6HAM_A.pdb "E"    "L"    "T"    "T"    "R"    "K"    "D"   
pdbs/split_chain/4K46_A.pdb "D"    "L"    "V"    "I"    "R"    "E"    "D"   
pdbs/split_chain/4NP6_A.pdb "D"    "L"    "V"    "I"    "R"    "E"    "D"   
pdbs/split_chain/3GMT_A.pdb "P"    "L"    "V"    "Q"    "R"    "D"    "D"   
pdbs/split_chain/4PZL_A.pdb "P"    "L"    "I"    "T"    "R"    "T"    "D"   
                            [,169] [,170] [,171] [,172] [,173] [,174] [,175]
pdbs/split_chain/1AKE_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/4X8M_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/6S36_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/6RZE_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/4X8H_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/3HPR_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/1E4V_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/5EJE_A.pdb "D"    "Q"    "E"    "E"    "C"    "V"    "R"   
pdbs/split_chain/1E4Y_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/3X2S_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/6HAP_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/6HAM_A.pdb "D"    "Q"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/4K46_A.pdb "D"    "K"    "E"    "E"    "T"    "V"    "L"   
pdbs/split_chain/4NP6_A.pdb "D"    "K"    "E"    "E"    "T"    "V"    "R"   
pdbs/split_chain/3GMT_A.pdb "D"    "K"    "E"    "E"    "T"    "V"    "K"   
pdbs/split_chain/4PZL_A.pdb "D"    "N"    "E"    "D"    "T"    "V"    "K"   
                            [,176] [,177] [,178] [,179] [,180] [,181] [,182]
pdbs/split_chain/1AKE_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/4X8M_A.pdb "K"    "R"    "L"    "V"    "E"    "W"    "H"   
pdbs/split_chain/6S36_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/6RZE_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/4X8H_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/3HPR_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/1E4V_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/5EJE_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/1E4Y_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/3X2S_A.pdb "K"    "R"    "L"    "C"    "E"    "Y"    "H"   
pdbs/split_chain/6HAP_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/6HAM_A.pdb "K"    "R"    "L"    "V"    "E"    "Y"    "H"   
pdbs/split_chain/4K46_A.pdb "A"    "R"    "L"    "G"    "V"    "Y"    "H"   
pdbs/split_chain/4NP6_A.pdb "A"    "R"    "L"    "N"    "V"    "Y"    "H"   
pdbs/split_chain/3GMT_A.pdb "K"    "R"    "L"    "D"    "V"    "Y"    "E"   
pdbs/split_chain/4PZL_A.pdb "Q"    "R"    "L"    "S"    "V"    "Y"    "H"   
                            [,183] [,184] [,185] [,186] [,187] [,188] [,189]
pdbs/split_chain/1AKE_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/4X8M_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/6S36_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/6RZE_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/4X8H_A.pdb "Q"    "M"    "T"    "A"    "A"    "L"    "I"   
pdbs/split_chain/3HPR_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/1E4V_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/5EJE_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/1E4Y_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/3X2S_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/6HAP_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/6HAM_A.pdb "Q"    "M"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/4K46_A.pdb "N"    "Q"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/4NP6_A.pdb "T"    "Q"    "T"    "A"    "P"    "L"    "I"   
pdbs/split_chain/3GMT_A.pdb "A"    "Q"    "T"    "K"    "P"    "L"    "I"   
pdbs/split_chain/4PZL_A.pdb "A"    "Q"    "T"    "A"    "K"    "L"    "I"   
                            [,190] [,191] [,192] [,193] [,194] [,195] [,196]
pdbs/split_chain/1AKE_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/4X8M_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/6S36_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/6RZE_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/4X8H_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/3HPR_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/1E4V_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/5EJE_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/1E4Y_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/3X2S_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/6HAP_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/6HAM_A.pdb "G"    "Y"    "Y"    "S"    "K"    "E"    "A"   
pdbs/split_chain/4K46_A.pdb "A"    "Y"    "Y"    "G"    "K"    "E"    "A"   
pdbs/split_chain/4NP6_A.pdb "E"    "Y"    "Y"    "G"    "K"    "E"    "A"   
pdbs/split_chain/3GMT_A.pdb "T"    "Y"    "Y"    "G"    "D"    "W"    "A"   
pdbs/split_chain/4PZL_A.pdb "D"    "F"    "Y"    "R"    "N"    "F"    "S"   
                            [,197] [,198] [,199] [,200] [,201] [,202] [,203]
pdbs/split_chain/1AKE_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/4X8M_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/6S36_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/6RZE_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/4X8H_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/3HPR_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/1E4V_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/5EJE_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/1E4Y_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/3X2S_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/6HAP_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/6HAM_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/4K46_A.pdb "E"    "A"    "G"    "N"    "T"    "-"    "-"   
pdbs/split_chain/4NP6_A.pdb "A"    "A"    "G"    "K"    "T"    "-"    "-"   
pdbs/split_chain/3GMT_A.pdb "R"    "R"    "G"    "A"    "E"    "-"    "-"   
pdbs/split_chain/4PZL_A.pdb "S"    "T"    "N"    "T"    "K"    "I"    "P"   
                            [,204] [,205] [,206] [,207] [,208] [,209] [,210]
pdbs/split_chain/1AKE_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/4X8M_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/6S36_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/6RZE_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/4X8H_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/3HPR_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/1E4V_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/5EJE_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/1E4Y_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/3X2S_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/6HAP_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/6HAM_A.pdb "K"    "Y"    "A"    "K"    "V"    "D"    "G"   
pdbs/split_chain/4K46_A.pdb "Q"    "Y"    "L"    "K"    "F"    "D"    "G"   
pdbs/split_chain/4NP6_A.pdb "Q"    "Y"    "L"    "K"    "F"    "D"    "G"   
pdbs/split_chain/3GMT_A.pdb "-"    "-"    "-"    "-"    "-"    "N"    "G"   
pdbs/split_chain/4PZL_A.pdb "K"    "Y"    "I"    "K"    "I"    "N"    "G"   
                            [,211] [,212] [,213] [,214] [,215] [,216] [,217]
pdbs/split_chain/1AKE_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/4X8M_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/6S36_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/6RZE_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/4X8H_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/3HPR_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/1E4V_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/5EJE_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/1E4Y_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/3X2S_A.pdb "T"    "K"    "P"    "V"    "A"    "E"    "V"   
pdbs/split_chain/6HAP_A.pdb "T"    "K"    "P"    "V"    "C"    "E"    "V"   
pdbs/split_chain/6HAM_A.pdb "T"    "K"    "P"    "V"    "C"    "E"    "V"   
pdbs/split_chain/4K46_A.pdb "T"    "K"    "A"    "V"    "A"    "E"    "V"   
pdbs/split_chain/4NP6_A.pdb "T"    "K"    "Q"    "V"    "S"    "E"    "V"   
pdbs/split_chain/3GMT_A.pdb "L"    "K"    "A"    "P"    "A"    "-"    "-"   
pdbs/split_chain/4PZL_A.pdb "D"    "Q"    "A"    "V"    "E"    "K"    "V"   
                            [,218] [,219] [,220] [,221] [,222] [,223] [,224]
pdbs/split_chain/1AKE_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/4X8M_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/6S36_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/6RZE_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/4X8H_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/3HPR_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/1E4V_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/5EJE_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/1E4Y_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/3X2S_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/6HAP_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/6HAM_A.pdb "R"    "A"    "D"    "L"    "E"    "K"    "I"   
pdbs/split_chain/4K46_A.pdb "S"    "A"    "E"    "L"    "E"    "K"    "A"   
pdbs/split_chain/4NP6_A.pdb "S"    "A"    "D"    "I"    "A"    "K"    "A"   
pdbs/split_chain/3GMT_A.pdb "-"    "-"    "-"    "Y"    "R"    "K"    "I"   
pdbs/split_chain/4PZL_A.pdb "S"    "Q"    "D"    "I"    "F"    "D"    "Q"   
                            [,225] [,226] [,227]
pdbs/split_chain/1AKE_A.pdb "L"    "G"    "-"   
pdbs/split_chain/4X8M_A.pdb "L"    "G"    "-"   
pdbs/split_chain/6S36_A.pdb "L"    "G"    "-"   
pdbs/split_chain/6RZE_A.pdb "L"    "G"    "-"   
pdbs/split_chain/4X8H_A.pdb "L"    "G"    "-"   
pdbs/split_chain/3HPR_A.pdb "L"    "G"    "-"   
pdbs/split_chain/1E4V_A.pdb "L"    "G"    "-"   
pdbs/split_chain/5EJE_A.pdb "L"    "G"    "-"   
pdbs/split_chain/1E4Y_A.pdb "L"    "G"    "-"   
pdbs/split_chain/3X2S_A.pdb "L"    "G"    "-"   
pdbs/split_chain/6HAP_A.pdb "L"    "G"    "-"   
pdbs/split_chain/6HAM_A.pdb "L"    "G"    "-"   
pdbs/split_chain/4K46_A.pdb "L"    "A"    "-"   
pdbs/split_chain/4NP6_A.pdb "L"    "A"    "-"   
pdbs/split_chain/3GMT_A.pdb "S"    "G"    "-"   
pdbs/split_chain/4PZL_A.pdb "L"    "N"    "K"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>pdbs<span class="sc">$</span>xyz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Total Frames#: 16
   Total XYZs#:   681,  (Atoms#:  227)

    [1]  NA  NA  NA  &lt;...&gt;  15.818  46.771  47.7  [10896] 

+ attr: Matrix DIM = 16 x 681</code></pre>
</div>
</div>
<p>Summary view of the alignments: The gray areas showed the aligned blocks while the white demonstrates gaps in the alignments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector containing PDB codes for figure axis</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">basename.pdb</span>(pdbs<span class="sc">$</span>id)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw schematic alignment</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pdbs, <span class="at">labels=</span>ids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>And collect annotation for each entry</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>anno <span class="ot">&lt;-</span> <span class="fu">pdb.annotate</span>(ids)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(anno)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       structureId chainId macromoleculeType chainLength experimentalTechnique
1AKE_A        1AKE       A           Protein         214                 X-ray
4X8M_A        4X8M       A           Protein         214                 X-ray
6S36_A        6S36       A           Protein         214                 X-ray
6RZE_A        6RZE       A           Protein         214                 X-ray
4X8H_A        4X8H       A           Protein         214                 X-ray
3HPR_A        3HPR       A           Protein         214                 X-ray
       resolution       scopDomain                   pfam         ligandId
1AKE_A       2.00 Adenylate kinase Adenylate kinase (ADK)              AP5
4X8M_A       2.60             &lt;NA&gt; Adenylate kinase (ADK)             &lt;NA&gt;
6S36_A       1.60             &lt;NA&gt; Adenylate kinase (ADK) CL (3),NA,MG (2)
6RZE_A       1.69             &lt;NA&gt; Adenylate kinase (ADK)    NA (3),CL (2)
4X8H_A       2.50             &lt;NA&gt; Adenylate kinase (ADK)             &lt;NA&gt;
3HPR_A       2.00             &lt;NA&gt; Adenylate kinase (ADK)              AP5
                                          ligandName                source
1AKE_A              BIS(ADENOSINE)-5'-PENTAPHOSPHATE      Escherichia coli
4X8M_A                                          &lt;NA&gt;      Escherichia coli
6S36_A CHLORIDE ION (3),SODIUM ION,MAGNESIUM ION (2)      Escherichia coli
6RZE_A               SODIUM ION (3),CHLORIDE ION (2)      Escherichia coli
4X8H_A                                          &lt;NA&gt;      Escherichia coli
3HPR_A              BIS(ADENOSINE)-5'-PENTAPHOSPHATE Escherichia coli K-12
                                                                                                                                                                     structureTitle
1AKE_A STRUCTURE OF THE COMPLEX BETWEEN ADENYLATE KINASE FROM ESCHERICHIA COLI AND THE INHIBITOR AP5A REFINED AT 1.9 ANGSTROMS RESOLUTION: A MODEL FOR A CATALYTIC TRANSITION STATE
4X8M_A                                                                                                                   Crystal structure of E. coli Adenylate kinase Y171W mutant
6S36_A                                                                                                                   Crystal structure of E. coli Adenylate kinase R119K mutant
6RZE_A                                                                                                                   Crystal structure of E. coli Adenylate kinase R119A mutant
4X8H_A                                                                                                                   Crystal structure of E. coli Adenylate kinase P177A mutant
3HPR_A                                                                                               Crystal structure of V148G adenylate kinase from E. coli, in complex with Ap5A
                                                    citation rObserved  rFree
1AKE_A                Muller, C.W., et al. J Mol Biol (1992)    0.1960     NA
4X8M_A               Kovermann, M., et al. Nat Commun (2015)    0.2491 0.3089
6S36_A                 Rogne, P., et al. Biochemistry (2019)    0.1632 0.2356
6RZE_A                 Rogne, P., et al. Biochemistry (2019)    0.1865 0.2350
4X8H_A               Kovermann, M., et al. Nat Commun (2015)    0.1961 0.2895
3HPR_A Schrank, T.P., et al. Proc Natl Acad Sci U S A (2009)    0.2100 0.2432
        rWork spaceGroup
1AKE_A 0.1960  P 21 2 21
4X8M_A 0.2463    C 1 2 1
6S36_A 0.1594    C 1 2 1
6RZE_A 0.1819    C 1 2 1
4X8H_A 0.1914    C 1 2 1
3HPR_A 0.2062  P 21 21 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(anno<span class="sc">$</span>source)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Escherichia coli"                                
[2] "Escherichia coli K-12"                           
[3] "Escherichia coli O139:H28 str. E24377A"          
[4] "Escherichia coli str. K-12 substr. MDS42"        
[5] "Photobacterium profundum"                        
[6] "Vibrio cholerae O1 biovar El Tor str. N16961"    
[7] "Burkholderia pseudomallei 1710b"                 
[8] "Francisella tularensis subsp. tularensis SCHU S4"</code></pre>
</div>
</div>
<p>Time for PCA. We will use not the <code>prcomp()</code> function from base R, but the <code>pca()</code> function from the <code>bio3d</code> package as this one is designed to work nicely with biomolecular data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>pc.xray <span class="ot">&lt;-</span> <span class="fu">pca</span>(pdbs)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pc.xray)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can now focus on PC1 vs PC2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pc.xray, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s cluster our structures</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate RMSD</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> <span class="fu">rmsd</span>(pdbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in rmsd(pdbs): No indices provided, using the 204 non NA positions</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Structure-based clustering</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>hc.rd <span class="ot">&lt;-</span> <span class="fu">hclust</span>(<span class="fu">dist</span>(rd))</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>grps.rd <span class="ot">&lt;-</span> <span class="fu">cutree</span>(hc.rd, <span class="at">k=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now my PC plot colored by clustering group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>grps.rd <span class="ot">&lt;-</span> <span class="fu">cutree</span>(hc.rd, <span class="at">k=</span><span class="dv">3</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pc.xray, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"grey50"</span>, <span class="at">bg=</span>grps.rd, <span class="at">pch=</span><span class="dv">21</span>, <span class="at">cex=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="class09_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="optional-further-visualization" class="level2">
<h2 class="anchored" data-anchor-id="optional-further-visualization">Optional further visualization</h2>
<p>To visualize the major structural variations in the ensemble the function mktrj() can be used to generate a trajectory PDB file by interpolating along a give PC (eigenvector):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize first principal component</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>pc1 <span class="ot">&lt;-</span> <span class="fu">mktrj</span>(pc.xray, <span class="at">pc=</span><span class="dv">1</span>, <span class="at">file=</span><span class="st">"pc_1.pdb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>